---
applications:
  coolservice:
    deployments:
      - name: develop
        url: api.run.mydomain.io --skip-ssl-validation
        org: devorg
        space: samplespace
        path: coolservice/development.yml
        push_cmd: cf push-zdd ${APP_NAME} 
      - name: production
        url: api.run.proddomain.io
        org: prodorg
        space: bigspace
        path: coolservice/production.yml
        push_cmd: cf push-zdd coolservice 

